/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface AppBackdrop {
    'open': () => void;
  }
  interface AppBackdropAttributes extends StencilHTMLAttributes {}

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppModal {
    'buttons': any;
    'content': string;
    'open': () => void;
    'title': string;
  }
  interface AppModalAttributes extends StencilHTMLAttributes {
    'buttons'?: any;
    'content'?: string;
    'title'?: string;
  }

  interface AppProfile {
    'name': string;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppBackdrop': Components.AppBackdrop;
    'AppHome': Components.AppHome;
    'AppModal': Components.AppModal;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
  }

  interface StencilIntrinsicElements {
    'app-backdrop': Components.AppBackdropAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-modal': Components.AppModalAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
  }


  interface HTMLAppBackdropElement extends Components.AppBackdrop, HTMLStencilElement {}
  var HTMLAppBackdropElement: {
    prototype: HTMLAppBackdropElement;
    new (): HTMLAppBackdropElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppModalElement extends Components.AppModal, HTMLStencilElement {}
  var HTMLAppModalElement: {
    prototype: HTMLAppModalElement;
    new (): HTMLAppModalElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLElementTagNameMap {
    'app-backdrop': HTMLAppBackdropElement
    'app-home': HTMLAppHomeElement
    'app-modal': HTMLAppModalElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
  }

  interface ElementTagNameMap {
    'app-backdrop': HTMLAppBackdropElement;
    'app-home': HTMLAppHomeElement;
    'app-modal': HTMLAppModalElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
